### ISSUE TITLE
PJSIP uses wrong IP in FROM headers

### ISSUE THREAD

**Issue by alfred-vilsmeier** [asterisk/pjproject#20]
Hi, we have an asterisk 13 box with PJSIP 2.4.5. Everything works great with a single NIC (eth0), but we recently added a SIP Trunk connected directly via a second NIC (eth1). There's a transport bound to each IP with the correct local_net and external IP addresses.
Our SIP phones register to the asterisk box but the FROM header in the replies has the wrong IP address and all contacts now appear as unavailable, qualify shows  them as unreachable, extensions are never rung from call queues with ringinuse disabled, etc.
Please advise.

[pjsip wrong ip in from.txt](https://github.com/asterisk/pjproject/files/208447/pjsip.wrong.ip.in.from.txt)

**Comment by jcolp** [comment]
Please use the asterisk-users mailing list or https://community.asterisk.org/ site for help with Asterisk.

**Comment by alfred-vilsmeier** [comment]
Well, the actual headers are handled by PJSIP entirely, are they not?

Perhaps I'm approaching this the wrong way but I think the real issue lies with how PJSIP is evaluating the information to include in the headers.

Thank you.

**Comment by jcolp** [comment]
No, Asterisk constructs and determines what headers to put in. As well it is unlikely that the From header would be the problem. It's not used for routing. It's more likely the Contact header or the underlying routing of the software itself.

**Comment by alfred-vilsmeier** [comment]
Well, both Contact and Via headers are fine.
I will post in the asterisk forums and update the entry here if anything comes up, thank you!
