### ISSUE TITLE
createRecorder API fails when called from Python via SWIG

### ISSUE THREAD

**Issue by havstrucker** [asterisk/pjproject#22]
While I am able to create an audio player,

Code:

	import pjsua2 as pj
	player = pj.AudioMediaPlayer()
	player.createPlayer("/home/anirudh/Music/message.wav")

Log:

	21:33:57.886    pjsua_aud.c  Creating file player: /home/anirudh/Music/message.wav..
	21:33:57.886   wav_player.c  .File player '/home/anirudh/Music/message.wav' created: samp.rate=16000, ch=1, bufsize=4KB, filesize=56KB
	21:33:57.886    pjsua_aud.c  .Player created, id=0, slot=1

I am not able to create an audio recorder which has similar interface

Code:

	import pjsua2 as pj
	recorder = pj.AudioMediaRecorder()
	recorder.createRecorder("/home/anirudh/Music/message.wav")

Log:

	Traceback (most recent call last):
	  File "main.py", line 143, in <module>
		pjsua2_test()
	  File "main.py", line 97, in pjsua2_test
		recorder.createRecorder("/home/anirudh/Music/message.wav")
	  File "/home/anirudh/.local/lib/python2.7/site-packages/pjsua2.py", line 4813, in createRecorder
		return _pjsua2.AudioMediaRecorder_createRecorder(self, file_name, enc_type, max_size, options)
	NotImplementedError: Wrong number or type of arguments for overloaded function 'AudioMediaRecorder_createRecorder'.
	  Possible C/C++ prototypes are:
		pj::AudioMediaRecorder::createRecorder(pj::string const &,unsigned int,pj_ssize_t,unsigned int)
		pj::AudioMediaRecorder::createRecorder(pj::string const &,unsigned int,pj_ssize_t)
		pj::AudioMediaRecorder::createRecorder(pj::string const &,unsigned int)
		pj::AudioMediaRecorder::createRecorder(pj::string const &)

To see the interface of createPlayer, I purposely gave an invalid parameter, which threw an error as expected.

Code:

	import pjsua2 as pj
	player = pj.AudioMediaPlayer()
	player.createPlayer(0)

Log:

	Traceback (most recent call last):
	  File "main.py", line 143, in <module>
		pjsua2_test()
	  File "main.py", line 93, in pjsua2_test
		player.createPlayer(0)
	  File "/home/anirudh/.local/lib/python2.7/site-packages/pjsua2.py", line 4762, in createPlayer
		return _pjsua2.AudioMediaPlayer_createPlayer(self, file_name, options)
	NotImplementedError: Wrong number or type of arguments for overloaded function 'AudioMediaPlayer_createPlayer'.
	  Possible C/C++ prototypes are:
		pj::AudioMediaPlayer::createPlayer(pj::string const &,unsigned int)
		pj::AudioMediaPlayer::createPlayer(pj::string const &)

**Comment by jcolp** [comment]
This project is a mirror of PJSIP, we don't work on it 'nor is it monitored for issues. You will likely have better luck on the official mailing list, http://lists.pjsip.org/mailman/listinfo/pjsip_lists.pjsip.org

**Comment by havstrucker** [comment]
Shall do that. Thank you.
